#Include %A_ScriptDir%\Plugins\brackets.ahk
#Include %A_ScriptDir%\Plugins\edit.ahk
#Include %A_ScriptDir%\Plugins\google.ahk
#Include %A_ScriptDir%\Plugins\hotString.ahk
#Include %A_ScriptDir%\Plugins\keybdMouse.ahk
#Include %A_ScriptDir%\Plugins\launcher.ahk
#Include %A_ScriptDir%\Plugins\main.ahk
#Include %A_ScriptDir%\Plugins\numpad.ahk
#Include %A_ScriptDir%\Plugins\others.ahk
#Include %A_ScriptDir%\Plugins\temp.ahk
#Include %A_ScriptDir%\Plugins\toggle.ahk
