#Include *i %A_ScriptDir%\Plugins\brackets.ahk
#Include *i %A_ScriptDir%\Plugins\edit.ahk
#Include *i %A_ScriptDir%\Plugins\git_alias.ahk
#Include *i %A_ScriptDir%\Plugins\hotString.ahk
#Include *i %A_ScriptDir%\Plugins\IME.ahk
#Include *i %A_ScriptDir%\Plugins\keybdmouse.ahk
#Include *i %A_ScriptDir%\Plugins\main.ahk
#Include *i %A_ScriptDir%\Plugins\numpad.ahk
#Include *i %A_ScriptDir%\Plugins\others.ahk
#Include *i %A_ScriptDir%\Plugins\temp.ahk
#Include *i %A_ScriptDir%\Plugins\toggle.ahk
